In [3]:
import numpy as np

In [33]:
#Array 1d
d3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(d3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
d3.shape

(2, 2, 3)

In [35]:
d3.ndim

3

In [36]:
d3.dtype

dtype('int64')