In [1]:
import numpy as np

In [9]:
a = np.array([2,3,4 ])
b = np.array([2,3,4 ])

In [10]:
result = a + b
print(result)

[4 6 8]


In [13]:
c = np.array([[1,2,3,4], [5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
c[1,2]

np.int64(7)

In [15]:
c[0,:]

array([1, 2, 3, 4])

In [17]:
c[:, 1]

array([2, 6])